//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3DCytoFlow
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class x0033_DCytoFlowDBContainer : DbContext
    {
        public x0033_DCytoFlowDBContainer()
            : base("name=x0033_DCytoFlowDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Analysis> Analyses { get; set; }
        public virtual DbSet<Cluster> Clusters { get; set; }
    }
}
