//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3DCytoFlow
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analysis
    {
        public Analysis()
        {
            this.Clusters = new HashSet<Cluster>();
        }
    
        public int Id { get; set; }
        public string Date { get; set; }
        public string FcsFilePath { get; set; }
        public string FcsUploadDate { get; set; }
        public string ResultFilePath { get; set; }
        public string ResultDate { get; set; }
        public string Delta { get; set; }
    
        public virtual User User { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual ICollection<Cluster> Clusters { get; set; }
    }
}
