//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3DCytoFlow
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cluster
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string X { get; set; }
        public string Y { get; set; }
        public string Z { get; set; }
        public string Width { get; set; }
        public string Height { get; set; }
        public string Depth { get; set; }
    
        public virtual Analysis Analysis { get; set; }
    }
}
